Portfolio/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in:'login', sign_out:'logout', sign_up:'register'}
  resources :products, except: [:show]
  get 'products/:id', to: 'products#show', as: 'product/show'
  get 'angular-items', to: 'products#angular'



  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Portfolio/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Portfolio/app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title, :body
  belongs_to :topic
end

Portfolio/app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:,width:)
    "http://placehold.it/#{height}x#{width}"
  end
end

Portfolio/app/models/product.rb
class Product < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda {|attrs| attrs['name'].blank? }
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: "Angular")
  end

  scope :ruby_on_rails, -> {where(subtitle: "Ruby on Rails")}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

Portfolio/app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_badge

  def set_badge
    self.badge ||= Placeholder.image_generator(height: '250', width: '250')
  end
end

Portfolio/app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :product
end

Portfolio/app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title
  has_many :blogs
end

Portfolio/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

Portfolio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
end

Portfolio/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: "Post status has been updated"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

Portfolio/app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  def current_user
    super || guest_user
  end

  def guest_user
    OpenStruct.new(name: "Guest User",
                  first_name: "Guest",
                  last_name: "Guest",
                  email: "guest@example.com"
                  )
  end

end

Portfolio/app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

Portfolio/app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

Portfolio/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

Portfolio/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products_items = Product.all
  end

  def angular
    @angular_products_items = Product.angular
  end

  def new
    @product_item = Product.new
    3.times {@product_item.technologies.build }
  end

  def create
    @product_item = Product.new(take_params)

    respond_to do |format|
      if @product_item.save
        format.html {redirect_to products_path, notice: "Your portfolio item is now live."}
      else
        format.html { render :new}
      end
    end
  end


  def edit
    @product_item = Product.find(params[:id])
  end

  def update
    @product_item = Product.find(params[:id])
    respond_to do |format|
      if @product_item.update(take_params)
        format.html { redirect_to products_path, notice: "The record is successfully updated."}
      else
        format.html {render :edit}
      end
    end
  end


  def show
    @product_item = Product.find(params[:id])
  end

  def destroy
    # Perform the look up
    @product_item = Product.find(params[:id])

    # Destroy / Delete the record
    @product_item.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to products_path, notice: "Post was removed"}
    end
  end
private

  def take_params
    params.require(:product).permit(:title,
                                    :subtitle,
                                    :body,
                                    technologies_attributes: [:name]
                                    )
  end

end

Portfolio/app/helpers/application_helper.rb
module ApplicationHelper
end

Portfolio/app/helpers/blogs_helper.rb
module BlogsHelper
end

Portfolio/app/helpers/pages_helper.rb
module PagesHelper
end

Portfolio/app/helpers/products_helper.rb
module ProductsHelper
end

Portfolio/app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Portfolio/app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

Portfolio/app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

Portfolio/app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

Portfolio/app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

Portfolio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if current_user.is_a?(User) %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Register", new_user_registration_path %>
      <%= link_to "Log in", new_user_session_path %>
    <% end %>
    <%= yield %>

    <% if session[:source] %>
    <p>Thanks for visiting me from <%= session[:source] %></p>
    <% end %>
  </body>
</html>

Portfolio/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

Portfolio/app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

Portfolio/app/views/pages/home.html.erb
<h1>Hi, <%= current_user.first_name %></h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blog Posts</h1>
<%= @posts.inspect%>

<h1>Skills</h1>
<%= @skills.inspect %>

Portfolio/app/views/products/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "CREATE A NEW ITEM", new_product_path %>

<% @angular_products_items.each do |product_item| %>
  <p><%= link_to product_item.title, product_path(product_item)%></p>
  <p><%= product_item.subtitle%></p>
  <p><%= product_item.body%></p>
  <%= image_tag product_item.thumb_image unless product_item.thumb_image.nil?%>
  <%= link_to "Edit", edit_product_path(product_item) %>
  <%= link_to "Delete Item", product_path(product_item), method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>

Portfolio/app/views/products/edit.html.erb
<h1>Edit this Portfolio Item</h1>

<%= form_for(@product_item) do |f| %>
  <div class = "field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class = "field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class = "field">
    <%= f.label :title %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

Portfolio/app/views/products/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "CREATE A NEW ITEM", new_product_path %>

<% @products_items.each do |product_item| %>
  <p><%= link_to product_item.title, product_path(product_item)%></p>
  <p><%= product_item.subtitle%></p>
  <p><%= product_item.body%></p>
  <%= image_tag product_item.thumb_image unless product_item.thumb_image.nil?%>
  <%= link_to "Edit", edit_product_path(product_item) %>
  <%= link_to "Delete Item", product_path(product_item), method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>

Portfolio/app/views/products/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%= form_for(@product_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  <ul>
    <%= f.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>

    <% end %>
  </ul>

  <div class="action">
    <%= f.submit %>
  </div>

  <% end %>

Portfolio/app/views/products/show.html.erb
<%= image_tag @product_item.main_image %>

<h1><%= @product_item.title %><h1>

<em><%= @product_item.subtitle %></em>

<p><%= @product_item.body %> </p>

<h2> Technologies Used </h2>
<% @product_item.technologies.each do |t| %>
<li><%=t.name%></li>
<% end %>